name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JQ
        run: sudo apt-get install -y jq

      - name: Fetch and Update Commit Count
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          total_commits=0
          page=1
          while :; do
            repos=$(curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/repos?per_page=100&page=$page | jq -r '.[].full_name')
            [ -z "$repos" ] && break
            for repo in $repos; do
              commit_count=$(curl -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$repo/commits?per_page=1 | jq '. | length')
              total_commits=$((total_commits + commit_count))
            done
            page=$((page + 1))
          done
          echo "Total commits: $total_commits"
          # Update the README file with the new commit count
          sed -i "s/Total Commits: [0-9k]*/Total Commits: ${total_commits}/" README.md
          
      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update total commits in README"
          git push
