name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JQ
        run: sudo apt-get install -y jq

      - name: Fetch and Update Commit Count
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          total_commits=0
          page=1
          while :; do
            echo "Fetching repos for page $page"
            repos=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/repos?per_page=100&page=$page | jq -r '.[].full_name')
            if [ -z "$repos" ]; then
              echo "No more repositories found on page $page"
              break
            fi
            for repo in $repos; do
              echo "Processing repo: $repo"
              repo_commits=0
              commit_page=1
              while :; do
                echo "Fetching commits for repo $repo, page $commit_page"
                commits=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$repo/commits?per_page=100&page=$commit_page)
                if echo "$commits" | jq empty; then
                  commit_count=$(echo "$commits" | jq '. | length')
                  echo "Found $commit_count commits on page $commit_page for repo $repo"
                  if [ "$commit_count" -eq 0 ]; then
                    echo "No commits found on page $commit_page for repo $repo"
                    break
                  fi
                  repo_commits=$((repo_commits + commit_count))
                  commit_page=$((commit_page + 1))
                else
                  echo "Error fetching commits for repo $repo, page $commit_page"
                  break
                fi
              done
              echo "Total commits for repo $repo: $repo_commits"
              total_commits=$((total_commits + repo_commits))
            done
            page=$((page + 1))
          done
          echo "Total commits across all repos: $total_commits"
          # Update the README file with the new commit count
          sed -i "s/Total Commits: [0-9k]*/Total Commits: ${total_commits}/" README.md

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update total commits in README"
          git push
