name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Run waka-readme-stats with retry
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        retry:
          max-attempts: 3
          delay-seconds: 30
